- index: 0
  bmc: https://192.168.58.15:8080
  userPass: dummy:dummy
- index: 1
  bmc: https://192.168.13.146
  userPass: Administrator:superuser
- index: 2
  bmc: https://192.168.13.147
  userPass: Administrator:superuser
- index: 3
  bmc: https://192.168.13.148
  userPass: Administrator:superuser
- index: 4
  bmc: https://192.168.13.149
  userPass: Administrator:superuser
- index: 5
  bmc: https://192.168.14.130
  userPass: Administrator:Redhat123!
- index: 6
  bmc: https://192.168.14.131
  userPass: Administrator:Redhat123!
- index: 7
  bmc: https://192.168.14.132
  userPass: Administrator:Redhat123!
- index: 8
  bmc: https://192.168.14.133
  userPass: Administrator:Redhat123!

